title: "Databases and SQL"
author: "P.E. Broeksma & P.J. Kamphuis"
only_build_toc_files: true

repository:
  url: https://github.com/<your-username>/databases-sql-book
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  home_page_in_navbar: true

execute:
  execute_notebooks: off
